### ISSUE TITLE
Video scaleToFill is not fast enough

### ISSUE THREAD

**Issue by ElchinValiyev** [Develolper/develolper#19]
js scales only after page is loaded, so one can notice the glitch ( video to rescale ). One solution is to use  ` object-fit: cover;` on video style, which is, however, not widely supported.

**Comment by BumbuKhan** [comment]
I've used this one https://coverr.co/, not sure what is currently used in our project...

**Comment by hasan-li** [comment]
Ребята, если есть проблемы, то берите и исправляйте. Все открыто

**Comment by ElchinValiyev** [comment]
Possible solution :
https://slicejack.com/fullscreen-html5-video-background-css/.  Will look into it later.

**Comment by BumbuKhan** [comment]
Guys, do not vaporize :-) include this plugin https://rishabhp.github.io/bideo.js/, this one is better
