### ISSUE TITLE
What about creating section 'Technologies we love & use'?

### ISSUE THREAD

**Issue by BumbuKhan** [Develolper/develolper#24]
Section should describe languages, frameworks and so forth we use in our projects.
We could put this section right after "// SERVICES" or somewhere below...
I see this section as below

![img_1827](https://cloud.githubusercontent.com/assets/19274459/24832604/0a30200e-1cc4-11e7-9d76-d94f660ebd89.JPG)

**Comment by hasan-li** [comment]
If you press "Learn more" in web Development section, you will be redirecting to technologies which we use


![image](https://cloud.githubusercontent.com/assets/11164894/24832906/2cbc02ae-1cbb-11e7-9f33-7ca635eff74f.png)


![image](https://cloud.githubusercontent.com/assets/11164894/24832920/64358f52-1cbb-11e7-9a7a-a67a8eb1afbd.png)

**Comment by BumbuKhan** [comment]
Sorry didn' notice
