### ISSUE TITLE
Contact us form

### ISSUE THREAD

**Issue by hasan-li** [Develolper/develolper#9]
Contact us form (db also needed)

**Comment by device999** [comment]
https://device999.github.io/Contact-Form/

Hasan take a look at this. Choose one of the 4 given :) i liked 4th 👍

**Comment by BumbuKhan** [comment]
Hi @device999 , we use bootstrap 4.x, all forms that you suggested use bootstrap 3.x

**Comment by device999** [comment]
@BumbuKhan i didn't notice that. So respectively these are out?

**Comment by BumbuKhan** [comment]
Definitely! we do not even need any 'ready to use' form. It's as easy as pie.
Actually I'm against of using Bootstrap 4 since it's on alfa, the latest version of 3.x is fully sufficient

**Comment by hasan-li** [comment]
I already added form! @device999 @BumbuKhan
